Repository openbrewerydb/openbrewerydb-laravel-api, pull requests merged in 2025-03, with the labels that each got.

#56 [Chore] Removed auth tests
  tests/Feature/Auth/AuthenticationTest.php
  tests/Feature/Auth/EmailVerificationTest.php
  tests/Feature/Auth/PasswordResetTest.php
  tests/Feature/Auth/RegistrationTest.php
Labels: 🧹 chore

#57 [Feature] Add endpoint to retrieve breweries metadata
  app/Http/Controllers/Api/V1/GetBreweriesMeta.php
  app/Http/Resources/V1/BreweryMetaResource.php
  routes/api/v1/routes.php
Labels: 🎉 feature

#58 [Chore] Update Laravel framework version to 11.44.1
  composer.json
  composer.lock
Labels: 🧹 chore

#59 [Chore] Update response handling and cache usage in brewery controllers
  app/Http/Controllers/Api/V1/GetBrewery.php
  app/Http/Controllers/Api/V1/RandomBrewery.php
  app/Http/Controllers/Api/V1/SearchBreweries.php
  routes/api/v1/routes.php
Labels: 🧹 chore

#21 Pest Tests (Initial)
  .gitignore
  app/Http/Controllers/Api/V1/GetBreweriesMeta.php
  app/Http/Controllers/Api/V1/ListBreweries.php
  app/Models/Traits/V1/BreweryFilters.php
  database/factories/BreweryFactory.php
  database/factories/UserFactory.php
  database/seeders/DatabaseSeeder.php
  phpunit.xml
  run-tests-with-coverage.sh
  tests/Feature/Api/ApiTestCase.php
  tests/Feature/Api/V1/GetBreweries/BasicTest.php
  tests/Feature/Api/V1/GetBreweries/CityFilterTest.php
  tests/Feature/Api/V1/GetBreweries/CountryFilterTest.php
  tests/Feature/Api/V1/GetBreweries/DistanceFilterTest.php
  tests/Feature/Api/V1/GetBreweries/ExcludeTypesTest.php
  tests/Feature/Api/V1/GetBreweries/IdFilterTest.php
  tests/Feature/Api/V1/GetBreweries/NameFilterTest.php
  tests/Feature/Api/V1/GetBreweries/PaginationTest.php
  tests/Feature/Api/V1/GetBreweries/PostalFilterTest.php
  tests/Feature/Api/V1/GetBreweries/SortingTest.php
  tests/Feature/Api/V1/GetBreweries/StateFilterTest.php
  tests/Feature/Api/V1/GetBreweries/TypeFilterTest.php
  tests/Feature/Api/V1/GetBreweriesMetaTest.php
  tests/Feature/Api/V1/GetBreweryTest.php
  tests/Feature/Api/V1/RandomBreweryTest.php
  tests/Feature/Api/V1/SearchBreweriesTest.php
  tests/Feature/ExampleTest.php
  tests/Pest.php
  tests/TestCase.php
  tests/Unit/ExampleTest.php
  tests/Unit/Providers/AppServiceProviderTest.php
Labels: 🎉 feature

#60 [Chore] Upgrade to Laravel 12
  README.md
  app/Models/Brewery.php
  composer.json
  composer.lock
Labels: 🧹 chore

#61 [Fix] Update JSON structure; keep all fields
  app/Http/Resources/V1/BreweryResource.php
  tests/Feature/Api/V1/GetBreweries/StateFilterTest.php
Labels: 🐛 bug

#50 [Feature] Added test-app job to CI pipeline
  .env.example
  .github/workflows/ci.yml
  tests/Feature/Api/V1/GetBreweries/BasicTest.php
  tests/Feature/Api/V1/SearchBreweriesTest.php
Labels: 🎉 feature

#64 [Bug] Fixed request validation
  app/Http/Controllers/Api/V1/ListBreweries.php
  app/Http/Controllers/Api/V1/SearchBreweries.php
  tests/Feature/Api/V1/SearchBreweriesTest.php
Labels: 🐛 bug

#65 [Bug] Need to validate per page on requests
  app/Http/Controllers/Api/V1/ListBreweries.php
  app/Http/Controllers/Api/V1/SearchBreweries.php
  tests/Feature/Api/V1/GetBreweries/BasicTest.php
  tests/Feature/Api/V1/GetBreweries/PaginationTest.php
  tests/Feature/Api/V1/SearchBreweriesTest.php
Labels: 🐛 bug

#66 [Bug] Implement brewery type validation and update request handling
  app/Http/Controllers/Api/V1/ListBreweries.php
  app/Rules/BreweryType.php
  tests/Feature/Api/V1/GetBreweries/ExcludeTypesTest.php
  tests/Feature/Api/V1/GetBreweries/TypeFilterTest.php
Labels: 🐛 bug

#67 [Feature] Improved coordinates validation
  app/Http/Controllers/Api/V1/ListBreweries.php
  app/Rules/Coordinates.php
  tests/Feature/Api/V1/GetBreweries/DistanceFilterTest.php
  tests/Feature/Api/V1/RandomBreweryTest.php
Labels: 🎉 feature

#70 [Chore] Refactored list breweries endpoint
  app/Http/Controllers/Api/V1/ListBreweries.php
  app/Models/Brewery.php
  app/Models/Traits/V1/BreweryFilters.php
  phpunit.xml
  tests/Feature/Api/V1/GetBreweries/CityFilterTest.php
  tests/Feature/Api/V1/GetBreweries/PaginationTest.php
  tests/Feature/Api/V1/GetBreweries/StateFilterTest.php
Labels: 🧹 chore

#76 [Chore] Add excimer PHP extension to Dockerfiles
  Dockerfile
  docker/8.4/Dockerfile
Labels: 🧹 chore

#72 [Feature] Add Sentry
  .env.example
  bootstrap/app.php
  composer.json
  composer.lock
  config/sentry.php
Labels: 🎉 feature

#77 2025-03-27 dependency updates
  .env.example
  composer.json
  composer.lock
Labels: 🧹 chore

#78 [Feature] Refresh search indexes during startup
  Dockerfile
  src/etc/entrypoint.d/60-obdb-automations.sh
Labels: 🎉 feature

#82 [Chore] Removed import data from the dockerfile
  Dockerfile
Labels: 🧹 chore

#83 [Feature] Add automated brewery data import in entrypoint script
  src/etc/entrypoint.d/60-obdb-automations.sh
Labels: 🎉 feature

#88 [Feature] Add autocomplete endpoint for breweries and redirect to search
  app/Http/Controllers/Api/V1/AutocompleteBreweries.php
  routes/api/v1/routes.php
Labels: 🎉 feature

#85 [Fix] Update CORS allowed origins to wildcard
  config/cors.php
Labels: 🐛 bug
